namespace Rhombus.Slowmo.GPhoto2.Native;

public enum CameraStorageType
{
    GP_STORAGEINFO_ST_UNKNOWN = 0,
    GP_STORAGEINFO_ST_FIXED_ROM = 1,
    GP_STORAGEINFO_ST_REMOVABLE_ROM = 2,
    GP_STORAGEINFO_ST_FIXED_RAM = 3,
    GP_STORAGEINFO_ST_REMOVABLE_RAM = 4,
}
