namespace Rhombus.Slowmo.Firmata;

public enum Tmc2209Command {
    Setup=0,
    SetHardwareEnablePin=1,
    Enable=2, Disable=3,
    SetMicrostepsPerStep=4,
    SetMicrostepsPerStepPowerOfTwo=5,
    SetRunCurrent=6,
    SetHoldCurrent=7,
    SetHoldDelay=8,
    SetAllCurrentValues=9,
    EnableDoubleEdge=10, DisableDoubleEdge=11,
    EnableInverseMotorDirection=12, DisableInverseMotorDirection=13,
    SetStandstillMode=14,
    EnableAutomaticCurrentScaling=15, DisableAutomaticCurrentScaling=16,
    EnableAutomaticGradientAdaptation=17, DisableAutomaticGradientAdaptation=18,
    SetPwmOffset=19,
    SetPwmGradient=20,
    SetPowerDownDelay=21,
    SetReplyDelay=22,
    MoveAtVelocity=23,
    MoveUsingStepDirInterface=24,
    EnableStealthChop=25, DisableStealthChop=26,
    SetStealthChopDurationThreshold=27,
    SetStallGuardThreshold=28,
    EnableCoolStep=29, DisableCoolStep=30,
    SetCoolStepCurrentIncrement=31,
    SetCoolStepMeasurementCount=32,
    SetCoolStepDurationThreshold=33,
    EnableAnalogCurrentScaling=34, DisableAnalogCurrentScaling=35,
    UseExternalSenseResistors=36, UseInternalSenseResistors=37,
    GetVersion=38,
    IsCommunicating=39,
    IsSetupAndCommunicating=40,
    IsCommunicatingButNotSetup=41,
    HardwareDisabled=42,
    GetMicrostepsPerStep=43,
}